[workspace]
members = [
    "src/atp",
    "packages/ic-nosql",
    "packages/ic-nosql/example-canister",
    "packages/ic-nosql/tests"
]
resolver = "2"

[workspace.dependencies]
ic-nosql = { path = "packages/ic-nosql" }
