[chains]

[chains."eip155:*"]
chain_id = "eip155:*"
name = "EIP155 Wildcard Chain"
native_asset = "slip44:60"
rpc_endpoints = []
explorer_url = ""
cryptographic_curve = ["secp256k1"]
is_testnet = false
assets = []

[chains."solana:*"]
chain_id = "solana:*"
name = "Solana Wildcard Chain"
native_asset = "slip44:501"
rpc_endpoints = []
explorer_url = ""
cryptographic_curve = ["ed25519"]
is_testnet = false
assets = []

[chains."bip122:*"]
chain_id = "bip122:*"
name = "BIP122 Wildcard Chain"
native_asset = ""
rpc_endpoints = []
explorer_url = ""
cryptographic_curve = ["secp256k1"]
is_testnet = false
assets = []

