[package]
name = "atp-chain-utils"
edition = "2021"
version.workspace = true
description = "Chain utilities for ATP(Account Transfer Protocol)"
license = "MIT"
keywords = ["caip", "blockchain", "protocol", "atp", "account-transfer-protocol"]
categories = [
    "web-programming",
    "cryptography",
    "api-bindings",
    "wasm",
]
repository = "https://github.com/mycel-labs/atp"


[dependencies]
atp-caip = { workspace = true }
k256 = { version = "0.13.4", features = ["ecdsa"] }
sha3 = "0.10.8"
hex = "0.4.3"
bs58 = "0.5.1"
sha2 = "0.10.9"
ripemd = "0.1.3"

