[package]
name = "example-canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ic-nosql = { path = "../." }
ic-stable-structures = "0.6.7"
ic-cdk = "0.17"
candid = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
