[package]
name = "example-canister"
version.workspace = true
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.release]
release = false

[dependencies]
ic-nosql = { workspace = true }
ic-stable-structures = "0.6.7"
ic-cdk = "0.17"
candid = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
