[package]
name = "chain-registry"
version.workspace = true
edition = "2021"

[dependencies]
caip = { path = "../caip" }
config = "0.15.11"
ethers-core = "2.0.14"
serde = "1.0.219"
thiserror = "2.0.12"
toml = "0.8.22"
serde_json = "1.0.140"
