[package]
name = "atp-chain-registry"
version.workspace = true
edition = "2021"
description = "Chain registry for ATP (Account Transfer Protocol) to manage blockchain configurations and metadata."
license = "MIT"
keywords = ["caip", "blockchain", "configuration", "atp"]
categories = [
    "web-programming",
    "cryptography",
    "api-bindings",
    "wasm",
]
repository = "https://github.com/mycel-labs/atp"

[lib]
name = "atp_chain_registry"
path = "src/lib.rs"

[dependencies]
atp-caip = { workspace = true }
config = "0.15.11"
ethers-core = "2.0.14"
serde = "1.0.219"
thiserror = "2.0.12"
toml = "0.8.22"
serde_json = "1.0.140"
