[package]
name = "atp-chain-registry"
version.workspace = true
edition = "2021"
description = "Chain registry for blockchain network configuration"
license = "MIT"
keywords = ["blockchain", "registry", "configuration"]
categories = ["web-programming"]
repository = "https://github.com/mycel-labs/atp"


[dependencies]
atp-caip = { workspace = true }
config = "0.15.11"
ethers-core = "2.0.14"
serde = "1.0.219"
thiserror = "2.0.12"
toml = "0.8.22"
serde_json = "1.0.140"
